language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g npm@latest
script:
  - npm install --global expo-cli
  - npm ci
  - npx jest --ci
  - npm test
  - npm run build
after_success:
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
